### ISSUE TITLE
filenode not work properly

### ISSUE THREAD

**Issue by muhanstudio** [anyproto/any-sync-dockercompose#10]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [x] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

After deploying on Linux public server and filling the generated configuration to the client, the files can't be synchronized properly, the articles and emoji can be synchronized, but after inserting the image files, it will be stuck in sync, I suspect it has something to do with s3 emulator, because I observe the logs of the S3 emulator, and I found that it only receives the records of my two requests with python, and no anytype filenode write log (see picture), hopefully can come out an official more complete tutorial, such as heart. yml fill rule.In addition to this, I also observed that my self-hosted backup node is zero kb on the mobile side and infinity on the computer
![image](https://github.com/anyproto/any-sync-dockercompose/assets/29907393/b01a2f08-e712-4f0c-83ee-e1c997853eb4)
![image](https://github.com/anyproto/any-sync-dockercompose/assets/29907393/5d959948-1ce9-4c8a-8dad-41b9920e5af4)
![image](https://github.com/anyproto/any-sync-dockercompose/assets/29907393/99a779c9-b47b-4f6f-9720-7e0ebffb40b3)
![481B7Q N1G9I U 8567}JV1](https://github.com/anyproto/any-sync-dockercompose/assets/29907393/b20346eb-e770-4c12-9a19-fb1de5982e15)

### Expected Behavior

I want container generated network. filenode in yml is valid and S3 emulator can receive requests correctly or filenode can receive files correctly and request S3 emulator, if it is because of emulator, I would like to provide the option to configure my own S3 bucket
![image](https://github.com/anyproto/any-sync-dockercompose/assets/29907393/429f4cb0-1505-4ad8-9d05-e7330c9c1dd3)

### Steps To Reproduce

1. Clone the official any-sync-dockercompose library to your Debian hard drive 
2. cd to this directory 
3. make start Wait for deployment to complete 
4. Open etc/network.yml. 
5. Use any-sync-tools_0.0. 4_amd64. deb generate profile heart.yml 
6.  Use the etc/network.yml to replace the Docker-generated configuration information it contains with the corresponding content in the heart.yml (because I use sync-network to enter directly and then fill in the correct information manually). For example, according to the network ID, peerID, port, etc. Corresponding to the type, the IP address is also changed to the public network IP of the Linux server.
7. Test the public network connectivity of each port through ping, all ports are normal, and all ports can be accessed from the public network
8. heart.yml upload to the client, and create a new user, start trying to synchronize operations, such as changing documents, uploading files 
9.  And then there's these problems that I'm talking about.

### Environment

```markdown
- OS:Debian
- Version:12
```

**Comment by muhanstudio** [comment]
Is this a user error? It's still a bug. The official doesn't seem to have a mature deployment document.

**Comment by muhanstudio** [comment]
I'm sure it's the filenode problem now, because I stop or even delete the any-filenode container, and the result is the same as when I deploy all the containers normally (make start), and the result is that once the file is uploaded, it gets stuck. This means that filenode doesn't seem to be working at all.Thank you for providing this Docker image so that anytype users have more choices. This is very much in line with the concept of anytype. I am now a loyal fan of anytype. I hope the team can solve this problem when they have time.

**Comment by fb929** [comment]
hi!
I think the problem is in the internal "docker network".
Servers should be available for the clients on same ip addresses, which were recorded in "network config" ([mongodb](https://github.com/anyproto/puppet-anysync?tab=readme-ov-file#ahow-current-config-in-mongo)).
It means, that clients should be deployed in the same docker-compose.

**Comment by Supporterino** [comment]
All server are exposed with their respective IP adresses which are set inside the clients config. Or do you mean that the ips inside client and server confs need to be the same. If that is the case I can try that. My load balancer can handle that.

**Comment by ToaHartor** [comment]
I had the same problem with a MinIO instance, but managed to solve it by adding a file storage limit to the coordinator config, for instance (here 1GB) :
```yaml
fileLimit:
  limitDefault: 1073741824
  limitAlphaUsers: 10737418240
  limitNightlyUsers: 53687091200
```

**Comment by fb929** [comment]
I'm added setting "EXTERNAL_LISTEN_HOST", by default it's 127.0.0.1.
you can set LAN ip or PUBLIC internet ip (if you have).
