### ISSUE TITLE
(Self-hosted) When attempting to connect from different computers, the connection cannot be established

### ISSUE THREAD

**Issue by sai07100** [anyproto/any-sync-dockercompose#102]
[crash_2024-10-22T16_02_54.log](https://github.com/user-attachments/files/17495775/crash_2024-10-22T16_02_54.log)
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

On the host machine that serves as the server, I can create accounts and Self-hosted shows a yellow light. However, when attempting to connect from computers on other networks, the connection fails.
When I try to connect from another computer to create a different account, the Self-hosted status light is red.
When attempting to connect from different computers, the connection cannot be established, and shortly afterwards, this crash log pops up (Self-hosted). 

### Expected Behavior

Normal connections and creating new accounts

### Steps To Reproduce

1.Installing docker & make

2.In the target folder, use CMD command: git clone [GitHub - anyproto/any-sync-dockercompose: docker-compose for testing any-sync](https://github.com/anyproto/any-sync-dockercompose.git)

3.Create .env.override file Copy .env.override.stage1 and rename it Then add:
EXTERNAL_LISTEN_HOSTS= Enter IP #My Public IPv4: Check IP at https://www.whatismyip.com/
STORAGE_DIR=C:/Anytype_any-sync/Anytype #storage location

4.Modify .env.default:
ANY_SYNC_COORDINATOR_DEFAULT_LIMITS_SPACE_MEMBERS_READ=100000
ANY_SYNC_COORDINATOR_DEFAULT_LIMITS_SPACE_MEMBERS_WRITE=100000
ANY_SYNC_COORDINATOR_DEFAULT_LIMITS_SHARED_SPACES_LIMIT=100000

5.Run: git config --global core.autocrlf false

6.make start

7.Upload the any-sync-dockercompose/etc/client.yml file to Anytype
Log in

### Environment

```markdown
- OS:windows11 --linked–> windows10
- Version:0.42.8
```

### Anything else?

OS version: win32 x64 10.0.19045
App version: 0.42.8
Build number: build on 2024-09-06 10:41:02 +0000 UTC at #c583602e975eaf2e525ef7f22e4700f8825a6420 (dirty)
Library version: v0.35.7
Anytype Identity: A6PY9MQZ8UBZqPAp88PzM5y1GgARujKDaURi3zzeep7jGX4g
Analytics ID: 159b3da7-d474-4a85-839e-a227ddb3a9b8
Device ID: 12D3KooWLjCQaFXUrk2fVh4Sb19w7M8XZB7TEWbCsehDcxnNyEvg

This is information from the server’s host machine.
Another computer cannot connect and log in to this account.

**Comment by fb929** [comment]
The error is occurring because we are currently updating the "release".
I will release the updated versions for self-hosted a bit later.

**Comment by fb929** [comment]
https://github.com/anyproto/any-sync-dockercompose/releases/tag/v6.0.0
