### ISSUE TITLE
Anytype 43.0.1 stopped syncing with an existing any-sync-dockercompose setup

### ISSUE THREAD

**Issue by bytersproblem** [anyproto/any-sync-dockercompose#103]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Not able to sync with my setup of docker images

### Expected Behavior

To sync

### Steps To Reproduce

Red light in the desktop clinet on linux on the icon for the selfhosted setup. The data doesn't sync. Repeated the whole build process and still no changes. With open ports and without (via tailscale VPN, with subnets exposed). I will assist in solving by sending log data.
Thanks

### Environment

```markdown
- OS: ubuntu 
- Version: 24.04 server
```

**Comment by requilence** [comment]
@bytersproblem We have updated the any-sync protocol version and it's no longer compatible with the latest version released yesterday within the app. 

You need to upgrade your self-hosted setup. https://github.com/anyproto/any-sync-dockercompose/wiki/Upgrade-Guide

**Comment by bytersproblem** [comment]
It seems tha the answer is here #102 
I will close.

**Comment by bytersproblem** [comment]
I am still experiencing errors. What if I install version 5 from scrach, is it olny the default 
```
git clone ....
edit .env.override for external hosts
make start
```
or something else?

**Comment by itribs** [comment]
> I am still experiencing errors. What if I install version 5 from scrach, is it olny the default
> 
> ```
> git clone ....
> edit .env.override for external hosts
> make start
> ```
> 
> or something else?

Looks like the new version still hasn't been released

**Comment by fb929** [comment]
https://github.com/anyproto/any-sync-dockercompose/releases/tag/v6.0.0

**Comment by TaoRone** [comment]
The update has been tried and successfully made update twice, no need to modify other settings
