### ISSUE TITLE
Helm Chart Support for Self-Hosted Deployments

### ISSUE THREAD

**Issue by DmitriySmirnov** [anyproto/any-sync-dockercompose#106]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

While Docker Compose is a reliable option for many self-hosting enthusiasts, a significant number of users are managing their home labs on Kubernetes (k8s). Deploying containerized applications is typically straightforward, but any-sync presents a unique challenge due to its multiple dependencies. Users running Kubernetes clusters need a more standardized way to deploy and manage any-sync.

### Suggested solution

Please provide a Helm chart as an additional deployment option alongside Docker Compose.

**Comment by fb929** [comment]
I can’t think of a single reason why Kubernetes would be needed to deploy on a home single server.
Anyway, our application is not adapted for use in Kubernetes: almost all components require static routing and persistent storage.
Therefore, we do not plan to support a Helm chart for the server side.
