### ISSUE TITLE
Don't do "docker system prune" with "make clean"

### ISSUE THREAD

**Issue by marcolaux** [anyproto/any-sync-dockercompose#108]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Doing a `docker system prune` does clean everything on the system and is not related to this project.

### Suggested solution

There should be at least a warning that if one does `make clean` that this command invokes `docker system prune` and cleans all unused volumes, networks and images.

Additionally point the user to an URL so they can read into it what this means.

**Comment by fb929** [comment]
This was added intentionally and is meant for clearing the test environment.
Let me remind you that the primary purpose of this repository is testing.
