### ISSUE TITLE
Unable to generate config 

### ISSUE THREAD

**Issue by bolavefasfas** [anyproto/any-sync-dockercompose#11]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [ ] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

```
docker compose exec mongo-1 mongosh coordinator
db.nodeConf.find().sort( { _id: -1 } ).limit(1)
```

## Output
```
Current Mongosh Log ID:	659d18edb9b1db871b8c1283
Connecting to:		mongodb://127.0.0.1:27017/coordinator?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.0.1
MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017
bash: syntax error near unexpected token `.sort'
```

### Expected Behavior

It should be able to generate config right ?
All container started 
https://github.com/anyproto/any-sync-dockercompose?tab=readme-ov-file#usage
Storage and etc folder were also created 

### Steps To Reproduce

git clone https://github.com/anyproto/any-sync-dockercompose
make start
docker compose exec mongo-1 mongosh coordinator
db.nodeConf.find().sort( { _id: -1 } ).limit(1)

### Environment

```markdown
- OS: Ubuntu 20.04
- Version: 20.04
```

### Anything else?

I tried to host it in multiple diffrent x86 devices
A photo guide will be helpful.

**Comment by bolavefasfas** [comment]
Lovely thanks 

I was able to generate .yml and use to join selfhosted netowrk and create a new user for loggin in 

though it still shows 1 gb space in remote storage
<img width="469" alt="image" src="https://github.com/anyproto/any-sync-dockercompose/assets/82230241/1b8f0034-3a6c-4e27-a057-d32bdc619248">

Shoudnt it be the size of my disk in vps where I am running the any-sync ?
What am I missing ?
how do i get more storage 
I want to use my vps to store the notes and use it to sync 

Thanks

**Comment by fuksman** [comment]
Hey @bolavefasfas, the file limit for identities should be defined in the coordinator-node config. It's 1GB by default, and there is no automatic logic like "get the whole disk size as a limit." We will update our images to provide larger file limits for self-hosters by default.

**Comment by bolavefasfas** [comment]
> Hey @bolavefasfas, the file limit for identities should be defined in the coordinator-node config. It's 1GB by default, and there is no automatic logic like "get the whole disk size as a limit." We will update our images to provide larger file limits for self-hosters by default.

can we make it as a env variable in docker-compose.yml 
would be a lot easier.
Thanks for reply.

**Comment by fb929** [comment]
@bolavefasfas https://github.com/anyproto/any-sync-dockercompose/blob/main/.env#L41

**Comment by Onefabis** [comment]
@fb929 your link is broken, because of new file structure. Did you mean that lines that could be changed in order to increase the limit? https://github.com/anyproto/any-sync-dockercompose/blob/ddf4f9b9cc6d3759babad34fda47f0724e834f9d/.env.common#L45C1-L47C61

**Comment by fb929** [comment]
> @fb929 your link is broken, because of new file structure. Did you mean that lines that could be changed in order to increase the limit? https://github.com/anyproto/any-sync-dockercompose/blob/ddf4f9b9cc6d3759babad34fda47f0724e834f9d/.env.common#L45C1-L47C61

this is "spaces" limits

the files limit is here: https://github.com/anyproto/any-sync-dockercompose/blob/ddf4f9b9cc6d3759babad34fda47f0724e834f9d/.env.common#L54
