### ISSUE TITLE
Golang requires 1.23 but 1.22 is found

### ISSUE THREAD

**Issue by ste-phil** [anyproto/any-sync-dockercompose#116]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When setting up a self-hosted anytype service using this [description](https://github.com/anyproto/any-sync-dockercompose/wiki/Usage),  it fails at the step `docker compose up -d`. 

The message is:
![image](https://github.com/user-attachments/assets/33e7196f-1352-41a2-a3cc-0936ecf81850)

I solved it by changing on line in the file `Dockerfile-generateconfig-anyconf` 
`FROM golang:1.22-alpine3.19` -> `FROM golang:1.23-alpine3.19`

### Expected Behavior

The docker containers should build and spin up successfully.

### Steps To Reproduce

1. Follow instructions from [here](https://github.com/anyproto/any-sync-dockercompose/wiki/Usage)
2. Running `docker compose up -d` should fail

### Environment

```markdown
- OS: Windows 11
- Version: 23H2 / 22635.4515
```

**Comment by mighty-sponge** [comment]
fixed in v6.1.0
https://github.com/anyproto/any-sync-dockercompose/releases/tag/v6.1.0
