### ISSUE TITLE
After update of the client to version 44.0 the connection to the selfhosted sync server 5.0.4 reports an error

### ISSUE THREAD

**Issue by bytersproblem** [anyproto/any-sync-dockercompose#118]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

does ont sync

### Expected Behavior

should sync

### Steps To Reproduce

updated version of docker setup as from the UpdateGuide
Client connected successfully before version 44.0

### Environment

```markdown
- OS: Ubuntu
- Version: 24.04
```

### Anything else?

the question is how to update to version 6. Thanks

**Comment by bytersproblem** [comment]
I managed to upgrade.
I first needed to do `git fetch` and then `git checkout v6.1.0`, Frome there the update process is the same is with verison 4 to version 5.
I'm closing.

**Comment by fb929** [comment]
I'm updated the commands in the wiki - https://github.com/anyproto/any-sync-dockercompose/wiki/Upgrade-Guide#upgrade-process
