### ISSUE TITLE
Missing exposed ports

### ISSUE THREAD

**Issue by indigo-sadland** [anyproto/any-sync-dockercompose#119]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Release v6.1.0 is missing "ports" part in **minio**, **mongo** and **redis** containers in `docker-compose.yml` so their ports aren't exposed.

### Expected Behavior

Ports should be exposed to external network.

### Steps To Reproduce

1. Clone the repository:
`git clone https://github.com/anyproto/any-sync-dockercompose.git`
2. Navigate to the project directory:
`cd any-sync-dockercompose`
3. Configuration:
For configuration, use the .env.override file.
For example, setting an external IP for listening:
`echo 'EXTERNAL_LISTEN_HOSTS=<yourExternalIp1> <yourExternalIp2' >> .env.override`
5. Run the project:
`make start`

### Environment

```markdown
- OS: Ubuntu 22.04
```

**Comment by fb929** [comment]
This was done for security reasons.
I added port configurations for Redis, Mongo, and Minio Admin in `docker-compose.yml` with access restricted to the host machine only.
If you also need external network access, use `docker-compose.override.yml` to override the configuration.
