### ISSUE TITLE
Access Anytype from Different Networks using tailscale/zerotire via Tailscale IP or Domain Exposure

### ISSUE THREAD

**Issue by bolavefasfas** [anyproto/any-sync-dockercompose#25]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [ ] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Hello, I am currently facing an issue with accessing Anytype when my devices are not connected to the same network. This becomes a problem when I am traveling, at the trip, or on a office, and I need to access Anytype.

All of my devices are connected via `Tailscale`, and I believe that if we can set the server's Tailscale IP (e.g., `100.65.65.65`) in the Docker Compose file or the environment file, it would be incredibly helpful. This would allow me to access Anytype from any device connected to my Tailscale network, regardless of my physical location.

Alternatively, I would like to suggest the ability to expose Anytype via a **domain** using
 ```
1. Cloudflare Tunnels or
2. Nginx Reverse Proxy Manager or 
3. Tailscale funnel
```
This would provide a more traditional remote access solution and could be beneficial for users who do not use Tailscale or a similar service.

Thank you for your time and consideration.

### Suggested solution

Ability to add servers additional tailscale ip like (100.65.65.65) - tailscale server ip

So that it should work in all devices conected to server 

or ability expose it to domain

**Comment by fb929** [comment]
hi!
you can use EXTERNAL_LISTEN_HOST in .env
https://github.com/anyproto/any-sync-dockercompose?tab=readme-ov-file#configuration

**Comment by bolavefasfas** [comment]
> hi! you can use EXTERNAL_LISTEN_HOST in .env https://github.com/anyproto/any-sync-dockercompose?tab=readme-ov-file#configuration

Thanks fb929,

I should set this to the tailscale ip right ?

EXTERNAL_LISTEN_HOST=100.65.65.65

And what should I do to expose it to domain 
With cloudlfare tunnels or Nginix Proxy manager ?

**Comment by TAT-Hins** [comment]
> > hi! you can use EXTERNAL_LISTEN_HOST in .env https://github.com/anyproto/any-sync-dockercompose?tab=readme-ov-file#configuration
> 
> Thanks fb929,
> 
> I was able to get it to work using tailscale ip.
> 
> And what should I do to expose it to domain With cloudlfare tunnels or Nginix Proxy manager ?



> > hi! you can use EXTERNAL_LISTEN_HOST in .env https://github.com/anyproto/any-sync-dockercompose?tab=readme-ov-file#configuration
> 
> Thanks fb929,
> 
> I was able to get it to work using tailscale ip.
> 
> And what should I do to expose it to domain With cloudlfare tunnels or Nginix Proxy manager ?

I think you can map the public domain to the specific IP address and port in your LAN by using Nginx Stream or similar tools.

**Comment by iammruni** [comment]
@bolavefasfas did you find a solution for this?
