### ISSUE TITLE
attachment is not synced

### ISSUE THREAD

**Issue by baddate** [anyproto/any-sync-dockercompose#32]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

upload a pdf files on client A, then go client B to check the pdf object, it always at Syncing status and file is broken

### Expected Behavior

attachment file sync is working

### Steps To Reproduce

1. upload a file
2. check it on another device

### Environment

```markdown
- OS:Win11
- Version:v0.39.0
```

**Comment by fb929** [comment]
@baddate all you clients it's win11 ?

**Comment by baddate** [comment]
> @baddate all you clients it's win11 ?

Win11 and iOS 17

**Comment by fb929** [comment]
did you setup external listen address ?
https://github.com/anyproto/any-sync-dockercompose?tab=readme-ov-file#configuration

by default, we have only 127.0.0.1 in listen address on server

**Comment by baddate** [comment]
> did you setup external listen address ? https://github.com/anyproto/any-sync-dockercompose?tab=readme-ov-file#configuration
> 
> by default, we have only 127.0.0.1 in listen address on server

yeah, I changed it to my server IP, and it appeared in the `client.yml`, like this:

![image](https://github.com/anyproto/any-sync-dockercompose/assets/37013819/715b2703-9d5d-45bc-8931-e14c363b2562)

**Comment by David-Melik** [comment]
I confirm this problem I Have the same with pictures for PDF and all kind of files ...

**Comment by fb929** [comment]
I found the problem and fixed it. Please update to release v3.0.0.
Also you need make migration - https://github.com/anyproto/any-sync-dockercompose/blob/main/UPGRADE.md#upgrading-from-v2xx-to-v3xx

**Comment by David-Melik** [comment]
Thank you it solved the problem for me !

**Comment by Yunp3** [comment]
Can I set multiple listening addresses?
For example:
Nodes:
-Addresses:
-Any sync node-1:1001
-192.168.1.15:1001
-10.199.199.5:1001

**Comment by fb929** [comment]
> Can I set multiple listening addresses? For example: Nodes: -Addresses: -Any sync node-1:1001 -192.168.1.15:1001 -10.199.199.5:1001

yes.
now we don't have support for configure it, but you can do it manual

**Comment by fb929** [comment]
@Yunp3
I'm added support for multiple listening addresses, please use this release: https://github.com/anyproto/any-sync-dockercompose/releases/tag/v4.0.0

**Comment by TaoRone** [comment]
> @Yunp3 I'm added support for multiple listening addresses, please use this release: https://github.com/anyproto/any-sync-dockercompose/releases/tag/v4.0.0

Dear fb929:
This problem has occurred again.
When I create a service on server A (which also has IPV4+IPV6) on the Internet, I log in with the generated client file on my home computer (Windows) and mobile phone (Android). If the computer and mobile phone are connected to the LAN at the same time, all attachments (pictures and videos) can be synchronized successfully.
But if I disconnect my phone from the local area network and use a 4G service provider signal, although I can synchronize text messages, the attachments on both sides cannot be synchronized, even if the synchronization status shows successful synchronization.
My environment configuration file is as follows:
```
AWS_ACCESS_KEY_ID=minio_access_key
AWS_SECRET_ACCESS_KEY=minio_secret_key
MINIO_BUCKET=minio-bucket
MINIO_PORT=12500
EXTERNAL_MINIO_PORT=${MINIO_PORT}
MINIO_WEB_PORT=12501
EXTERNAL_MINIO_WEB_PORT=${MINIO_WEB_PORT}

ANY_SYNC_NODE_VERSION=prod
ANY_SYNC_FILENODE_VERSION=prod
ANY_SYNC_COORDINATOR_VERSION=prod
ANY_SYNC_CONSENSUSNODE_VERSION=prod
ANY_SYNC_ADMIN_VERSION=latest

MONGO_VERSION=7.0.2
REDIS_VERSION=7.2.0-v6
MINIO_VERSION=RELEASE.2024-01-16T16-07-38Z

EXTERNAL_LISTEN_HOSTS="144.24.xxx.xxx"

ANY_SYNC_NODE_1_HOST=any-sync-node-1
ANY_SYNC_NODE_1_PORT=12502
ANY_SYNC_NODE_1_ADDRESSES=${ANY_SYNC_NODE_1_HOST}:${ANY_SYNC_NODE_1_PORT}
ANY_SYNC_NODE_1_QUIC_PORT=12503
ANY_SYNC_NODE_1_QUIC_ADDRESSES=${ANY_SYNC_NODE_1_HOST}:${ANY_SYNC_NODE_1_QUIC_PORT}

ANY_SYNC_NODE_2_HOST=any-sync-node-2
ANY_SYNC_NODE_2_PORT=12504
ANY_SYNC_NODE_2_ADDRESSES=${ANY_SYNC_NODE_2_HOST}:${ANY_SYNC_NODE_2_PORT}
ANY_SYNC_NODE_2_QUIC_PORT=12505
ANY_SYNC_NODE_2_QUIC_ADDRESSES=${ANY_SYNC_NODE_2_HOST}:${ANY_SYNC_NODE_2_QUIC_PORT}

ANY_SYNC_NODE_3_HOST=any-sync-node-3
ANY_SYNC_NODE_3_PORT=12506
ANY_SYNC_NODE_3_ADDRESSES=${ANY_SYNC_NODE_3_HOST}:${ANY_SYNC_NODE_3_PORT}
ANY_SYNC_NODE_3_QUIC_PORT=12507
ANY_SYNC_NODE_3_QUIC_ADDRESSES=${ANY_SYNC_NODE_3_HOST}:${ANY_SYNC_NODE_3_QUIC_PORT}

ANY_SYNC_COORDINATOR_HOST=any-sync-coordinator
ANY_SYNC_COORDINATOR_PORT=12508
ANY_SYNC_COORDINATOR_ADDRESSES=${ANY_SYNC_COORDINATOR_HOST}:${ANY_SYNC_COORDINATOR_PORT}
ANY_SYNC_COORDINATOR_QUIC_PORT=12509
ANY_SYNC_COORDINATOR_QUIC_ADDRESSES=${ANY_SYNC_COORDINATOR_HOST}:${ANY_SYNC_COORDINATOR_QUIC_PORT}
ANY_SYNC_COORDINATOR_DEFAULT_LIMITS_SPACE_MEMBERS_READ=100000
ANY_SYNC_COORDINATOR_DEFAULT_LIMITS_SPACE_MEMBERS_WRITE=100000
ANY_SYNC_COORDINATOR_DEFAULT_LIMITS_SHARED_SPACES_LIMIT=100000

ANY_SYNC_FILENODE_HOST=any-sync-filenode
ANY_SYNC_FILENODE_PORT=12510
ANY_SYNC_FILENODE_ADDRESSES=${ANY_SYNC_FILENODE_HOST}:${ANY_SYNC_FILENODE_PORT}
ANY_SYNC_FILENODE_QUIC_PORT=12511
ANY_SYNC_FILENODE_QUIC_ADDRESSES=${ANY_SYNC_FILENODE_HOST}:${ANY_SYNC_FILENODE_QUIC_PORT}
ANY_SYNC_FILENODE_DEFAULT_LIMIT=1099511627776

ANY_SYNC_CONSENSUSNODE_HOST=any-sync-consensusnode
ANY_SYNC_CONSENSUSNODE_PORT=12512
ANY_SYNC_CONSENSUSNODE_ADDRESSES=${ANY_SYNC_CONSENSUSNODE_HOST}:${ANY_SYNC_CONSENSUSNODE_PORT}
ANY_SYNC_CONSENSUSNODE_QUIC_PORT=12513
ANY_SYNC_CONSENSUSNODE_QUIC_ADDRESSES=${ANY_SYNC_CONSENSUSNODE_HOST}:${ANY_SYNC_CONSENSUSNODE_QUIC_PORT}

MONGO_1_PORT=12514
MONGO_CONNECT=mongodb://mongo-1:${MONGO_1_PORT}
MONGO_REPLICA_SET=rs0
MONGO_URL=${MONGO_CONNECT}/?replicaSet=${MONGO_REPLICA_SET}

REDIS_HOST=redis
REDIS_PORT=12515
REDIS_URL="redis://${REDIS_HOST}:${REDIS_PORT}?dial_timeout=3&read_timeout=6s"

ANY_SYNC_ADMIN_HOST=0.0.0.0
ANY_SYNC_ADMIN_PORT=5000
EXTERNAL_ANY_SYNC_ADMIN_PORT=12516

```

**Comment by fb929** [comment]
Yes, changing the redis port did not work.
I made a fix: https://github.com/anyproto/any-sync-dockercompose/pull/58/commits/67e873932f3f4f4010f25c37c19b7a553ae4d5bc
