### ISSUE TITLE
s3 neccessary?

### ISSUE THREAD

**Issue by rubydesign** [anyproto/any-sync-dockercompose#36]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Documentation (README)) does not speak about s3 , ie necessary prerequisites. 
Other places mention s3, and sources use AAWS_XX so there is strong indication that s3 is needed

### Expected Behavior

I would expect **all** necessary prerequisites to be mentioned before installing, so users can evaluate wheather this is for them.  (Case in point is the docker installation, which is good, but quite obvious from the docker commands. )
Not sure if there are other prerequisites, but even if not, it would be nice to be explicit about it

### Steps To Reproduce

Is a doc bug, can only be evaluated by devs who know the system better than the docs

### Environment

```markdown
Current README
```

### Anything else?

I am very enthusiastic to try this out. I have been with anytype since alpha.
But the current pricing is just not for everyone, so it's great this option exists.

**Comment by rubydesign** [comment]
So in a burst of unlimited courage i just tried it out, and it seems no external dependencies are needed. 
Still, worth mentioning, in my humble newbie opinion

Also i would suggest to mention configuration *before* usage
And possibly add the EXTERNAL_ANY_SYNC_ADMIN_PORT , because 80 may be in use
(Maybe also mention REDIS_PORT)

Possibly clarify what EXTERNAL_LISTEN_HOST is, as opposed to ANY_SYNC_ADMIN_HOST

Is the @mighty-sponge taking it on, otherwise i'd also be happy to close this and leave it in the closed issues to find.

**Comment by mighty-sponge** [comment]
Thank you for noticing!
All services required for any-sync network operation are already defined in `docker-compose.yml`. As S3 we use the self-hosted Minio solution, integration with any cloud-based S3 services is also possible.

EXTERNAL_ANY_SYNC_ADMIN_PORT you can set to any port you have available.

EXTERNAL_LISTEN_HOST variable is described [here](https://github.com/anyproto/any-sync-dockercompose?tab=readme-ov-file#configuration).
