### ISSUE TITLE
create-bucket unable to create MinIO bucket

### ISSUE THREAD

**Issue by azaidi4** [anyproto/any-sync-dockercompose#37]
### Have you read a contributing guide?

- [x] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Container `any-sync-dockercompose-create-bucket-1` exits with the following error
```
mc: <ERROR> Unable to make bucket `minio/minio-bucket`. Put "http://minio:9111/minio-bucket/": dial tcp 172.21.0.3:9111: connect: connection refused
```
On viewing the web-ui for created MinIO instance, bucket `minio-bucket` is missing

### Expected Behavior

`any-sync-dockercompose-create-bucket-1` creates bucket and displays output of `mc mb minio/${MINIO_BUCKET}` in docker logs as instructed in docker-compose.yml

### Steps To Reproduce

1. `git clone` repo
2. Update `.env` 
```
- MINIO_PORT=9111
- MINIO_WEB_PORT=9180
- EXTERNAL_ANY_SYNC_ADMIN_PORT=82
- EXTERNAL_LISTEN_HOST="192.168.0.201"
```
3. `make start`

### Environment

```markdown
- OS: Debian GNU/Linux 12 (bookworm)
- Version: 3.0.0
```

### Anything else?

 I don't see the bucket being used even after creating `minio-bucket` bucket manually through minio web-ui. It is empty even after uploading some test files into my space.

**Comment by fb929** [comment]
yes, currently changing minio port is not working

> I don't see the bucket being used even after creating minio-bucket bucket manually through minio web-ui. It is empty even after uploading some test files into my space.

you need to wait 5 minutes or longer, this is bug for anytype-ts client version 0.39.0
