### ISSUE TITLE
Add ca-certificates to the filenode container to support connecting to https s3 storage.

### ISSUE THREAD

**Issue by Nyar233** [anyproto/any-sync-dockercompose#38]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

The filenode node cannot connect to the https s3 storage service due to the missing ca-certificates package.

### Expected Behavior

Add support for https connections to filenode nodes.

### Steps To Reproduce

Trying to use s3 storage connected via https.

### Environment

```markdown
- OS:debian
- Version:v3.0.0
```

### Anything else?

![image](https://github.com/anyproto/any-sync-dockercompose/assets/30363595/86a77686-aac8-43d8-96a6-2f274a131190)

_No response_

**Comment by fb929** [comment]
I'm added ca-certificates package, it's should be fine now
try to this filenode image version: https://github.com/anyproto/any-sync-filenode/releases/tag/v0.6.6
