### ISSUE TITLE
New account sync failed

### ISSUE THREAD

**Issue by xkord** [anyproto/any-sync-dockercompose#39]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

My first account works good
And the second one not sync. 

### Expected Behavior

Second account work properly

### Steps To Reproduce

1. Create first account using client.yml on self hosted server
2. Create second account - not synced

### Environment

```markdown
- OS: Ubuntu, Iphone
- Version: 22.04, 15
```

**Comment by xkord** [comment]
What I can do? Could this repo support multiple accounts in my self hosted docker environment?

**Comment by fb929** [comment]
I can't reproduce: I created two separate accounts, and both synced fine.

Account one:
<img width="1433" alt="Screenshot 2024-04-23 at 19 18 41" src="https://github.com/anyproto/any-sync-dockercompose/assets/1324020/23d8ec87-93b4-44a7-ba21-6e92cf0bad1e">
<img width="1433" alt="Screenshot 2024-04-23 at 19 24 33" src="https://github.com/anyproto/any-sync-dockercompose/assets/1324020/a3c71fd4-2665-4692-85df-4efe4038c540">

Account two:
<img width="1433" alt="Screenshot 2024-04-23 at 19 37 38" src="https://github.com/anyproto/any-sync-dockercompose/assets/1324020/77999af4-8722-4805-be21-4f76e28a0460">
<img width="1433" alt="Screenshot 2024-04-23 at 19 37 48" src="https://github.com/anyproto/any-sync-dockercompose/assets/1324020/dbdeffda-78ce-4097-9974-13307188c744">
