### ISSUE TITLE
Can not share space

### ISSUE THREAD

**Issue by StefanFabian** [anyproto/any-sync-dockercompose#49]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

I can not share my second space as it's greyed out and on hover shows
"You have to be online to share a space!"

### Expected Behavior

I should be able to share the space.

### Steps To Reproduce

1. Set to prod, changed EXTERNAL_LISTEN_HOSTS to a public facing IPv4 address (it has a firewall for connections from outside the local network but I am on the local network so there should be no communication issues)
2. Create vault
3. Create second space
4. Try to share

### Environment

```markdown
- OS: Ubuntu 20.04
- Version: main (07.05.2024)
```

**Comment by fuksman** [comment]
Hello @StefanFabian, looks like there was a bug in the Desktop app. Please try the alpha version, does it fix the problem? https://github.com/anyproto/anytype-ts/releases/tag/v0.40.12-alpha

**Comment by StefanFabian** [comment]
I've tried the alpha and have the same issue in `0.40.12-alpha`.

**Comment by fuksman** [comment]
@StefanFabian really sorry to hear that, investigating further. Thank you for the fast feedback!

**Comment by colorprint** [comment]
I have the same issue

**Comment by colorprint** [comment]
With 0.40.13 Alpha client it works fine

**Comment by colorprint** [comment]
With 0.40.13 alpha one user succesfully added using the invitation link, but for any other users when they click the invitation link, the app returns error: The link you have tried to use does not seem to work

**Comment by fuksman** [comment]
@colorprint thanks, checking

**Comment by fuksman** [comment]
@colorprint just in case: are you sure that other users who try to use your invitation link are connected to the same self-hosted network as you are?

**Comment by colorprint** [comment]
> @colorprint just in case: are you sure that other users who try to use your invitation link are connected to the same self-hosted network as you are?

yes, of course. I have removed the link and generated the new one, and only after this the second invited user was able to join the space... But as for as I understand, the link is not for one-time usage, it should work for all users?

**Comment by fuksman** [comment]
Thanks! It should work from the first time, we will check.

**Comment by fuksman** [comment]
Should be fixed already
