### ISSUE TITLE
make start failed, mongo container issue

### ISSUE THREAD

**Issue by colorprint** [anyproto/any-sync-dockercompose#51]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When doing make start, mongo container failed to start:

dependency failed to start: container any-sync-dockercompose-mongo-1-1 exited (132)
make: *** [Makefile:10: start] Error 1

### Expected Behavior

Expected to start normally

### Steps To Reproduce

git clone
make start

### Environment

```markdown
- OS: Ubuntu 
- Version: LTS 24.04
```

**Comment by r0ckychan** [comment]
I am running into this issue too. Checked by running mongo:7.0.2 alone, and shows that my CPU lacks AVX support.
I can switch to mongodb docker image 4.*, and change healthcheck in docker-compose.yml according to mongo:4.*. 
But somehow still not working properly.

**Comment by Easylemon24** [comment]
Hey, 

i also experienced this error using an x5650 Intel Xeon. I don't know what cpu you are currently using but depending on the age and model the reason might be that it doesn't support AVX. You can also check that if you manually run 

> docker compose up


This would be the response i received:
```sh
mongo-1-1                         | 
mongo-1-1                         | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
mongo-1-1                         |   see https://jira.mongodb.org/browse/SERVER-54407
mongo-1-1                         |   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
mongo-1-1                         |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
mongo-1-1                         | 
mongo-1-1 exited with code 132
```


This seems to be a fix for this:
https://github.com/anyproto/any-sync-dockercompose/issues/29#issue-2190159129

Note:
i weirdly had my .env change back to mongo version 7 after

>  make start

to fix this i just ran the following command.

> docker compose up -d

**Comment by fb929** [comment]
@colorprint Is your problem solved?

**Comment by Soukyuu** [comment]
Just in case someone runs into this in a VM: if your CPU has AVX support, you have to activate the avx flag in QEMU or set CPU type to "host".
