### ISSUE TITLE
修改端口后程序没有读取.env中的新端口运行

### ISSUE THREAD

**Issue by LiteCat0905** [anyproto/any-sync-dockercompose#53]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

我通过下方步骤修改了端口以及`EXTERNAL_LISTEN_HOSTS`后 生成的`client.yml`不是新的端口，同时`make logs`
![image](https://github.com/anyproto/any-sync-dockercompose/assets/101038478/609cd985-2cba-40c5-a80c-7f3284901666)
![image](https://github.com/anyproto/any-sync-dockercompose/assets/101038478/9f46ce49-0b0b-4bf9-b32f-d50fe9da06b1)

有这样的日志 同时我无法同步 一直显示加载中

![image](https://github.com/anyproto/any-sync-dockercompose/assets/101038478/f235e92c-e4f3-4b9b-bdff-995a7de2e116)

### Expected Behavior

程序内部按照 新生成的 .env中的端口请求响应的服务，client.yml按照新的端口生成

### Steps To Reproduce

```
rm -f .env.override
read -p "Enter your host addresses (separated by spaces): " && echo EXTERNAL_LISTEN_HOSTS=$REPLY >> .env.override
# Change EXTERNAL_LISTEN_HOSTS
echo ANY_SYNC_NODE_1_PORT=11001 >> .env.override
echo ANY_SYNC_NODE_1_QUIC_PORT=11011 >> .env.override
echo ANY_SYNC_NODE_2_PORT=11002 >> .env.override
echo ANY_SYNC_NODE_2_QUIC_PORT=11012 >> .env.override
echo ANY_SYNC_NODE_3_PORT=11003 >> .env.override
echo ANY_SYNC_NODE_3_QUIC_PORT=11013 >> .env.override
echo ANY_SYNC_COORDINATOR_PORT=11004 >> .env.override
echo ANY_SYNC_COORDINATOR_QUIC_PORT=11014 >> .env.override
echo ANY_SYNC_FILENODE_PORT=11005 >> .env.override
echo ANY_SYNC_FILENODE_QUIC_PORT=11015 >> .env.override
echo ANY_SYNC_CONSENSUSNODE_PORT=11006 >> .env.override
echo ANY_SYNC_CONSENSUSNODE_QUIC_PORT=11016 >> .env.override
sudo make generate_env
make start
```

### Environment

```markdown
- OS:CentOS 7
- Version:v4.0.2
```

### Anything else?

![image](https://github.com/anyproto/any-sync-dockercompose/assets/101038478/eeffb4d6-8c16-434d-9143-f5d7c206fcc2)

![image](https://github.com/anyproto/any-sync-dockercompose/assets/101038478/718bbfc0-c07b-416c-a6ba-36cb03915f50)
![image](https://github.com/anyproto/any-sync-dockercompose/assets/101038478/6fae9fa4-71dc-4ce9-992c-ec1d5e495b77)
![image](https://github.com/anyproto/any-sync-dockercompose/assets/101038478/2c45af05-678d-4a97-895a-0597552a743c)

**Comment by TaoRone** [comment]
兄弟，记得好歹翻译英语反馈啊……
修改.env.common就行
.env.override按照说明是用来版本控制的，不用改
另外，你的ip暴漏了

**Comment by fb929** [comment]
> 兄弟，记得好歹翻译英语反馈啊…… 修改.env.common就行 .env.override按照说明是用来版本控制的，不用改 另外，你的ip暴漏了

please, don't change .env.common
you need to change only .env.override

@LiteCat0905 Unfortunately, at the moment, it is not possible to change the ports in the network section without regenerating the entire network configuration.
This will lead to a change in the networkId and incompatibility with previously launched clients.

You can do this by executing the following commands:
**!!! WARNING you'll lost all your data!!!**
 ```
make stop && make cleanEtcStorage && make start
```

**Comment by LiteCat0905** [comment]
> > 兄弟，记得好歹翻译英语反馈啊…… 修改.env.common就行 .env.override按照说明是用来版本控制的，不用改 另外，你的ip暴漏了
> 
> 请不要更改 .env.common， 您只需要更改 .env.override
> 
> @LiteCat0905不幸的是，目前无法在不重新生成整个网络配置的情况下更改网络部分中的端口。 这将导致 networkId 发生变化，并且与之前启动的客户端不兼容。
> 
> 您可以通过执行以下命令来做到这一点： **！！！警告您将丢失所有数据！**
> 
> ```
> make stop && make cleanEtcStorage && make start
> ```

Thank you for your help, I successfully solved the problem! I'm very grateful!

**Comment by leleogere** [comment]
> `make stop && make cleanEtcStorage && make start`

How can the data be backed up before this command and restored afterward?

I can export a space to JSON or Protobuf, but how do I import back the exported space with the new configuration?

**Comment by fb929** [comment]
> > `make stop && make cleanEtcStorage && make start`
> 
> How can the data be backed up before this command and restored afterward?
> 
> I can export a space to JSON or Protobuf, but how do I import back the exported space with the new configuration?

When this command is executed, the networkId is regenerated, which means it will be a new network.
At the moment, we do not have a mechanism to transfer data between networks on the server side.
However, you can do this on the client side: export the data on the client, regenerate the network, create a new account in the new network, and import the data.
