### ISSUE TITLE
a simple question about yamux and quic ports

### ISSUE THREAD

**Issue by TaoRone** [anyproto/any-sync-dockercompose#55]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

I'm sorry, my knowledge of computer networks is not solid enough, but after my search, I would like to ask a simple question:
Can't yamux and quic ports be the same
In theory, one is TCP and the other is UDP, should it be possible to set them to the same port simultaneously?
However, during actual deployment, the required configuration files cannot be generated.

Actually, my current network conditions only have 15 ports available for me to use, so I will try to use the fewest ports to achieve this great project~

### Expected Behavior

Successfully on the basis of the same port (such as yamux and
Quic uses 10000 at the same time)

### Steps To Reproduce

I tried running this project on different ports first, and it worked fine.
Then make stop make clean and make start
Project tip:
Container any sync dockercompose any sync coordinator bootstrap service 'any sync coordinator bootstrap' did not complete successfully: exit 139.4s coordinator

### Environment

```markdown
- OS:debian
- Version:12
```

**Comment by fb929** [comment]
Yes, it is possible. And after these changes, it even works.
https://github.com/anyproto/any-sync-dockercompose/commit/ea4bd985ae57c7b6793e5a3850cc1356196afe62
https://github.com/anyproto/any-sync-dockercompose/commit/be138faf23b96310429b83d02d9b85f270070320

Execute the following commands:
```
cat <<EOF >> .env.override
ANY_SYNC_NODE_1_QUIC_PORT=1001
ANY_SYNC_NODE_2_QUIC_PORT=1002
ANY_SYNC_NODE_3_QUIC_PORT=1003
ANY_SYNC_COORDINATOR_QUIC_PORT=1004
ANY_SYNC_FILENODE_QUIC_PORT=1005
ANY_SYNC_CONSENSUSNODE_QUIC_PORT=1006
EOF

make restart
```

**Comment by fb929** [comment]
@TaoRone Is your problem solved?

**Comment by TaoRone** [comment]
> @TaoRone Is your problem solved?

Forgive me for not testing in time... because I once gave up self-deployment,
But I remembered this great project again today, and re-deployed and tested, yes, your modification is valid, now the tcp and udp ports can be reused!
Celebrate! Very happy!
