### ISSUE TITLE
nodes.yml file doesn't exist in tmp/generateconfig after `make start`

### ISSUE THREAD

**Issue by ncgl-git** [anyproto/any-sync-dockercompose#6]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

`make start` and/or `make update` result in 
```
sed 's|^|    |; 1s|^|network:\n|' tmp/generateconfig/nodes.yml > tmp/etc/network.yml
sed: can't read tmp/generateconfig/nodes.yml: No such file or directory
make: *** [Makefile:9: generate_etc] Error 2
```

### Expected Behavior

Unless the documentation is missing, I expected the node.yml file to be generated in the tmp/generateconfig directory.

Am I supposed to create this file myself?

### Steps To Reproduce

Run:
`git clone https://github.com/anyproto/any-sync-dockercompose.git`
`cd any-sync-dockercompose`
`make start`

### Environment

```markdown
- OS: Windows 11 Pro
- Version: 22H2
```

**Comment by ncgl-git** [comment]
I am happy to update documentation via PR if this is user error too! Just let me know!

**Comment by fb929** [comment]
sorry, right now we don't have support of the host machines with Windows OS

**Comment by fb929** [comment]
@ncgl-git we added support windows system
do you can check, please ?
