### ISSUE TITLE
Can not synchronize with server node and other app clients(IOS, MacOS, windows11)

### ISSUE THREAD

**Issue by Luck-IT** [anyproto/any-sync-dockercompose#60]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Only create a new vault or first entry a vault can synced.

I use the project to deploy the server in docker environment, but only create a new vault or a app client enter a vault first, they can synchronize with server and client app. After that,  re-enter the vault, they cannot synchronize with server and client, showing syncing or prepare..., and the minio bucket no new object be added.

### Expected Behavior

Clients can synchronize with the server and each others.

### Steps To Reproduce

1. clone the repository
2. deployment use "make start"
3. change the ip in etc/client.yml to server ip
4. upload the client.yml to app, change self-host
5. create a new vault, and write some text, and add some pictures.
6. for a moment, the app show synced, check the minio bucket has some objects.
7. exit the app, and re-entry the vault, it shows Syncing or Preparing
8. use another app link the self-host, and entry the vault, after a moment, it shows Synced.
9. exit  the app and re-entry the  vault, it freezes Syncing or Preparing

### Environment

```markdown
- OS: Ubuntu
- Version:22.04
- docker compose version: v2.27.0
- IOS: 0.29.3
- windows11: 0.40.9
```

### Anything else?

here is client.yml, the realty file replace IP 127.0.0.1 to real IP
<img width="544" alt="屏幕截图 2024-05-25 015652" src="https://github.com/anyproto/any-sync-dockercompose/assets/10141767/0c3c90a1-e990-4bbe-921d-09bb511b68a0">

**Comment by Luck-IT** [comment]
Thank you, it my problem.
I add the server IP in .env.overrider file, and  build again, that works!

**Comment by tod-zhang** [comment]
> Thank you, it my problem. I add the server IP in .env.overrider file, and build again, that works!

Hi, can you tell me how to do it?

It is my steps:

1. cd any-sync-dockercompose
2. nano .env
3. add this record: EXTERNAL_LISTEN_HOSTS=123.123.123.123 （Assuming 123.123.123.123 is my VPS IP4 address）

**Comment by jiubai123** [comment]
> 谢谢，这是我的问题。我在 .env.overrider 文件中添加了服务器 IP，然后再次构建，这有效！

How can I find this file? Can you provide the path to this file?

**Comment by fb929** [comment]
> Hi, can you tell me how to do it?
> 
> It is my steps: 1.change the ip in etc/client.yml to server ip 2. open the file: env.overrider.prod 3. add this record: EXTERNAL_LISTEN_HOSTS=server ip

You need to follow these steps:
1. open the file: env.overrider and set `EXTERNAL_LISTEN_HOSTS=<your server ip>`
2. run `make restart`
3. copy the file `etc/client.yml` to the clients and run the application with this config.

**Comment by Luck-IT** [comment]
> > Hi, can you tell me how to do it?
> > It is my steps: 1.change the ip in etc/client.yml to server ip 2. open the file: env.overrider.prod 3. add this record: EXTERNAL_LISTEN_HOSTS=server ip
> 
> You need to follow these steps:
> 
> 1. open the file: env.overrider and set `EXTERNAL_LISTEN_HOSTS=<your server ip>`
> 2. run `make restart`
> 3. copy the file `etc/client.yml` to the clients and run the application with this config.

The file(.env.overrider) may be created by yourself, then add `EXTERNAL_LISTEN_HOSTS=<your server ip>`...
