### ISSUE TITLE
Key phrase or password protect network

### ISSUE THREAD

**Issue by StefanFabian** [anyproto/any-sync-dockercompose#62]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Knowing an anysync network's IP means you can create a space there.
This opens it up for malicious / unwanted use by random people.

### Suggested solution

Add authentication to allow securing the synchronization server.

**Comment by fb929** [comment]
At the moment, we don't have authentication mechanisms.
You can use a VPN and firewall to restrict access to your Anytype network.
