### ISSUE TITLE
Getting the error: failed to run node can't init service 'config'

### ISSUE THREAD

**Issue by Onefabis** [anyproto/any-sync-dockercompose#68]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When I created new docker compose make for the any-sync container, and created .env.override with the next code:
```
ANY_SYNC_NODE_VERSION=prod
ANY_SYNC_FILENODE_VERSION=prod
ANY_SYNC_COORDINATOR_VERSION=prod
ANY_SYNC_CONSENSUSNODE_VERSION=prod
EXTERNAL_LISTEN_HOSTS=192.168.88.69
```
I'm getting that error, when I try to login with 'Self-hosted mode' on Win11
![Anytype_240610181045](https://github.com/anyproto/any-sync-dockercompose/assets/13187447/26e8ba62-87c0-485a-a969-da0c9a504504)

### Expected Behavior

Win11 desktop app should be connected to the Server on login

### Steps To Reproduce

1. Install Win anytype app
2. Setup self-host docker https://github.com/anyproto/any-sync-dockercompose?tab=readme-ov-file
3. Put server address in .env.override EXTERNAL_LISTEN_HOSTS=your server ip
4. Try to login in the app

### Environment

```markdown
- OS: Win 11
- Version: 0.40.34-beta
```

**Comment by fb929** [comment]
Are you encountering this error when creating a new account in the self-hosted network?
Or are you trying to connect to the self-hosted network with an account from our public network?

**Comment by Onefabis** [comment]
@fb929 yes, I'm trying to login with existed account from public network

**Comment by fb929** [comment]
that is not possible: accounts from the public network and the self-hosted network are not compatible.
You need to create a new account in the self-hosted network
