### ISSUE TITLE
Any way to backup existing anytype docker container

### ISSUE THREAD

**Issue by Onefabis** [anyproto/any-sync-dockercompose#71]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

In case my HDD will die, I'll loose my data on the server, but I want to recover my generated container from 'make start' command at some point.

### Suggested solution

Could you provide any info how could I backup the whole docker container or maybe some files from it, so I could replace them in the new HDD drive so my device, that has latest data could update it to the server with old Network ID, so I don't need to create new account for that purpose, but use the old one instead.

**Comment by fb929** [comment]
You only need to back up the contents of the ./storage directory (or STORAGE_DIR if you changed the settings) in any convenient way.
it is best to do this by stopping all services, something like this:
```
make stop
cp -rp ./storage /path/to/backup/directory
make start
```

**Comment by Onefabis** [comment]
@fb929 another question similar to this topic, is there any way to restore account in case my device will change ID address: when it connected to another router or it changes network connection from LAN to Wifi?

**Comment by Onefabis** [comment]
@fb929 yeah, sorry, you're actually right. Last time I've tried that it didn't work with updated client.yml, this time it work well. Perhaps, I did something wrong that time. Thanks again!
