### ISSUE TITLE
Do not hardcode the numbers of sync nodes

### ISSUE THREAD

**Issue by hellodword** [anyproto/any-sync-dockercompose#75]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

https://github.com/anyproto/any-sync-dockercompose/blob/9609edfaecd2c2ee4859653c8780cf3e40410884/.env.common#L22-L38

https://github.com/anyproto/any-sync-dockercompose/blob/9609edfaecd2c2ee4859653c8780cf3e40410884/docker-generateconfig/anyconf.sh#L33-L35

https://github.com/anyproto/any-sync-dockercompose/blob/9609edfaecd2c2ee4859653c8780cf3e40410884/docker-generateconfig/anyconf.sh#L39-L41

https://github.com/anyproto/any-sync-dockercompose/blob/9609edfaecd2c2ee4859653c8780cf3e40410884/docker-generateconfig/anyconf.sh#L55-L56

https://github.com/anyproto/any-sync-dockercompose/blob/9609edfaecd2c2ee4859653c8780cf3e40410884/docker-generateconfig/processing.sh#L29

https://github.com/anyproto/any-sync-dockercompose/blob/9609edfaecd2c2ee4859653c8780cf3e40410884/docker-generateconfig/processing.sh#L39-L46

### Suggested solution

I'm not sure, maybe jinja2 is a good choice?

**Comment by fb929** [comment]
this will be too complicated: as it will also require simultaneous templating of docker-compose.yml files, .env, and the generator, along with post-processing configurations.
moreover, this does not align with the goals of this repository

**Comment by fb929** [comment]
The minimum number of any-sync-nodes required for the cluster to operate is 3.
Increasing this number is not practical because, architecturally, self-hosted can only operate within a single docker-host.
Additionally, at the moment, any-sync-node does not support rebalancing - you cannot change the number of nodes in an existing cluster, as this will lead to errors and potential data loss.
