### ISSUE TITLE
Second, third, etc. spaces doesn't sync

### ISSUE THREAD

**Issue by Onefabis** [anyproto/any-sync-dockercompose#82]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When I create second, third space they doesn't want to sync with the dockercompose. If I create it in the android Anytype 0.31.8 it just ends the sync process with 'No connection' status. If I create second space in Win11 Anytype 0.41.21-beta it just stuck at sync process in that space and furthermore it add the 'P2P Connection. Restricted' status as well.
![изображение](https://github.com/user-attachments/assets/ff48d0a1-5339-43a7-9927-1e3a24d44f96)

### Expected Behavior

All extra spaces, not only the first one should be synchronized with the dockercompose self-hosted tool.

### Steps To Reproduce

1. Install the latest Android App
2. Install the latest Anytype pre-release Win app
3. Install the latest dockercompose containers for the self-host sync
4. Try to sync the first space
5. Create the second space on the PC/Android
6. Check the sync status

### Environment

```markdown
- OS:Win11
- Version:0.41.21-beta

- OS:Android 10
- Version:0.31.8
```

**Comment by mighty-sponge** [comment]
Hey! I tried to follow your steps to create a space on the Win 0.41.21-beta client. I didn't find any problems: one space created on Windows, other on Android. These spaces and their contents were successfully synchronized between devices. Synchronization status permanently green.
To try and solve your problem, I request you to follow the steps below:
1. make sure that `EXTERNAL_LISTEN_HOST` address in the `.env` file is actually available to all clients on your network
2. be sure to use the latest release in the current repository or latest main branch. We fixed a critical bug on creating minio bucket
3. do not use VPNs or tunnels when working with any-sync-dockercompos - this has not been tested yet

In addition, attach the contents of your `.env` file in the comments. I want to make sure that your configuration is correct.

**Comment by Onefabis** [comment]
@mighty-sponge yes, sorry, you're absolutelly right. That was my fault. Unfortunately I didn't noticed that my SBC switched from Wifi connection to the Lan connection with another IP address. So I saw only P2P sync, not through self-hosted server. I've done with make stop/start with the new IP address and now extra spaces sync correctly. Sorry for taking your time. 
Will close the issue.

**Comment by Onefabis** [comment]
Closed
