### ISSUE TITLE
Remote storage become 1GB after re-login

### ISSUE THREAD

**Issue by MFYDev** [anyproto/any-sync-dockercompose#83]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

1. deploy the latest version, create a vault, login
2. see the remote storage is 1TB which is correct
3. log out of the vault
4. log in again
5. remote storage become 1GB

### Expected Behavior

remote storage should always be the 1TB

### Steps To Reproduce

1. deploy the latest version, create a vault, login
2. see the remote storage is 1TB which is correct
3. log out of the vault
4. log in again
5. remote storage become 1GB

### Environment

```markdown
- OS: Docker Compose remote ubuntu with Windows latest beta client
- Version:prod
```

**Comment by MFYDev** [comment]
Forgot to add, delete the local data folder and relogin, the remote storage become 1GB

**Comment by mighty-sponge** [comment]
Hi, I tried following your steps and I failed to detect the change of remote storage from 1TB to 1GB. I did login/logout, delete local and even minio data. As a result, I always got 1TB of remote storage.

To better understand the issue, please try again on the latest current beta (v0.41.39-beta) and also do a git pull of the current main branch. If that doesn't help, please describe in detail the steps to reproduce the problem and if you changed the .env file, specify which values.

**Comment by chiyi4488** [comment]
Hello @mighty-sponge,

My current .env setting is: `ANY_SYNC_FILENODE_DEFAULT_LIMIT=1099511627776`

As I understand it, this should be setting the limit to 1TB, but my Anytype shows only 1GB for Remote Storage. Am I misunderstanding the configuration?

By the way, my any-sync was deployed with the stable version just yesterday.

![image](https://github.com/user-attachments/assets/2269fb5a-9e1e-4300-8b40-42584cd8e5d1)

**Comment by lslvxy** [comment]
> Hello @mighty-sponge,
> 
> My current .env setting is: `ANY_SYNC_FILENODE_DEFAULT_LIMIT=1099511627776`
> 
> As I understand it, this should be setting the limit to 1TB, but my Anytype shows only 1GB for Remote Storage. Am I misunderstanding the configuration?
> 
> By the way, my any-sync was deployed with the stable version just yesterday.
> 
> ![image](https://private-user-images.githubusercontent.com/30853081/353301465-2269fb5a-9e1e-4300-8b40-42584cd8e5d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTk1NTYsIm5iZiI6MTcyMjQxOTI1NiwicGF0aCI6Ii8zMDg1MzA4MS8zNTMzMDE0NjUtMjI2OWZiNWEtOWUxZS00MzAwLThiNDAtNDI1ODRjZDhlNWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA5NDczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxZDExNjg5OTVjNjk3N2UwZjE1NjdkODNmMWVlZjYwYzM1OWQ4NzVhMzhkMDVkZWM4NzEzNzQyZDVlMzU3NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.chmOA9O9Z0zfSZiB92jgnMMDcILpjZnp82IdSVYMqzo)

Same as me

**Comment by fb929** [comment]
So I also cannot reproduce this.
my versions:
1. any-sync-dockercompose - v5.0.3
2. any-sync-* server versions:
    ```
    $ docker-compose ps --format "{{.Image}}"
    ghcr.io/anyproto/any-sync-consensusnode:v0.1.7
    ghcr.io/anyproto/any-sync-coordinator:v0.3.26
    ghcr.io/anyproto/any-sync-filenode:v0.6.5
    ghcr.io/anyproto/any-sync-node:v0.3.34
    ghcr.io/anyproto/any-sync-node:v0.3.34
    ghcr.io/anyproto/any-sync-node:v0.3.34
    minio/minio:RELEASE.2024-07-04T14-25-45Z
    mongo:7.0.2
    ghcr.io/anyproto/any-sync-tools:latest
    redis/redis-stack-server:7.2.0-v6
    ```
3. client version - 0.42.3 (macos)

**Comment by fb929** [comment]
> Forgot to add, delete the local data folder and relogin, the remote storage become 1GB
@MFYDev what exactly do you mean? Which specific folder are you deleting?

**Comment by MARTINrichard05** [comment]
I get the same thing.
I install the server using the getting started instructions, i create a space, then, log out and the limit goes to 1gb

**Comment by MARTINrichard05** [comment]
the container list : 
```f7669cf71bf5   ghcr.io/anyproto/any-sync-tools:latest               "tail -f /dev/null"      24 hours ago   Up 24 hours (healthy)   443/tcp, 8000/tcp, 8080/tcp                                                                                                                                                           any-sync-dockercompose-netcheck-1
e352345dc7e0   ghcr.io/anyproto/any-sync-node:v0.3.34               "/bin/sh -c '/bin/an…"   24 hours ago   Up 24 hours             443/tcp, 0.0.0.0:1002->1002/tcp, :::1002->1002/tcp, 0.0.0.0:1012->1012/udp, :::1012->1012/udp, 0.0.0.0:8002->8000/tcp, :::8002->8000/tcp, 0.0.0.0:8082->8080/tcp, :::8082->8080/tcp   any-sync-dockercompose-any-sync-node-2-1
c21e7771d879   ghcr.io/anyproto/any-sync-consensusnode:v0.1.7       "/bin/sh -c '/bin/an…"   24 hours ago   Up 24 hours             443/tcp, 8080/tcp, 0.0.0.0:1006->1006/tcp, :::1006->1006/tcp, 0.0.0.0:1016->1016/udp, :::1016->1016/udp, 0.0.0.0:8006->8000/tcp, :::8006->8000/tcp                                    any-sync-dockercompose-any-sync-consensusnode-1
14a54fa68fb3   ghcr.io/anyproto/any-sync-filenode:v0.7.2            "/bin/any-sync-filen…"   24 hours ago   Up 24 hours             443/tcp, 8080/tcp, 0.0.0.0:1005->1005/tcp, :::1005->1005/tcp, 0.0.0.0:1015->1015/udp, :::1015->1015/udp, 0.0.0.0:8004->8000/tcp, :::8004->8000/tcp                                    any-sync-dockercompose-any-sync-filenode-1
eee22d4cbf86   ghcr.io/anyproto/any-sync-node:v0.3.34               "/bin/sh -c '/bin/an…"   24 hours ago   Up 24 hours             443/tcp, 0.0.0.0:1003->1003/tcp, :::1003->1003/tcp, 0.0.0.0:1013->1013/udp, :::1013->1013/udp, 0.0.0.0:8003->8000/tcp, :::8003->8000/tcp, 0.0.0.0:8083->8080/tcp, :::8083->8080/tcp   any-sync-dockercompose-any-sync-node-3-1
7054c9d6f36e   ghcr.io/anyproto/any-sync-node:v0.3.34               "/bin/sh -c '/bin/an…"   24 hours ago   Up 24 hours             443/tcp, 0.0.0.0:1001->1001/tcp, :::1001->1001/tcp, 0.0.0.0:1011->1011/udp, :::1011->1011/udp, 0.0.0.0:8001->8000/tcp, :::8001->8000/tcp, 0.0.0.0:8081->8080/tcp, :::8081->8080/tcp   any-sync-dockercompose-any-sync-node-1-1
2aefa8b9da7d   ghcr.io/anyproto/any-sync-coordinator:v0.3.26        "/bin/any-sync-coord…"   24 hours ago   Up 24 hours             443/tcp, 8080/tcp, 0.0.0.0:1004->1004/tcp, :::1004->1004/tcp, 0.0.0.0:1014->1014/udp, :::1014->1014/udp, 0.0.0.0:8005->8000/tcp, :::8005->8000/tcp                                    any-sync-dockercompose-any-sync-coordinator-1
12065f5b4724   mongo:4.4.29                                         "docker-entrypoint.s…"   24 hours ago   Up 24 hours (healthy)   0.0.0.0:27001->27001/tcp, :::27001->27001/tcp, 27017/tcp                                                                                                                              any-sync-dockercompose-mongo-1-1
877cb5afa9e7   redis/redis-stack-server:7.2.0-v6                    "redis-server --port…"   24 hours ago   Up 24 hours (healthy)   0.0.0.0:6379->6379/tcp, :::6379->6379/tcp                                                                                                                                             any-sync-dockercompose-redis-1
fc29d17329a9   minio/minio:RELEASE.2024-07-04T14-25-45Z             "/usr/bin/docker-ent…"   24 hours ago   Up 24 hours (healthy)   0.0.0.0:9000-9001->9000-9001/tcp, :::9000-9001->9000-9001/tcp                                                                                                                         any-sync-dockercompose-minio-1
```

```
richou@server:~/any-sync-dockercompose$ cat .env.override
EXTERNAL_LISTEN_HOSTS=192.168.1.180
MONGO_VERSION=4.4.29
STORAGE_DIR="/mnt/ssd/anytype_data"
```

```
richou@server:~/any-sync-dockercompose$ cat docker-compose.override.yml
services:
  mongo-1:
    healthcheck:
      test: echo "rs.initiate({_id:'${MONGO_REPLICA_SET}',members:[{_id:0,host:\"mongo-1:${MONGO_1_PORT}\"}]}).ok || rs.status().ok" | mongo --port ${MONGO_1_PORT} --quiet
```

**Comment by fb929** [comment]
And can You also show a video from the client please?
a full cycle: create a new vault, show the limit and sync status, log out and log in again, and show the limit and sync status again.
