### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by bolavefasfas** [anyproto/any-sync-dockercompose#9]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [ ] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

 ```
=> ERROR [generator 5/5] RUN ./generate_config.sh                                                                                                                                                                                      0.3s
------
 > [generator 5/5] RUN ./generate_config.sh:
0.278 Network created
0.278 NetworkId:        N7o3ioCXEHD7Tg61NVrQtAHtCt16EqUb5BKUEi9ephwg2pQ6
0.278 ConfigurationId:  658fbaf8f50a160008a7d31d
0.282 Create network
0.295 ./generate_config.sh: line 10: /usr/bin/yq: cannot execute binary file: Exec format error
0.296 Failed network creations!
------
Dockerfile-generateconfig:8
--------------------
   6 |     WORKDIR /opt/generateconfig
   7 |     COPY --chmod=777 docker-generateconfig/generate_config.sh .env .
   8 | >>> RUN ./generate_config.sh
   9 |
  10 |     FROM alpine:3.18.4
--------------------
ERROR: failed to solve: process "/bin/sh -c ./generate_config.sh" did not complete successfully: exit code: 1
make: *** [Makefile:5: generate_config] Error 1
```

### Expected Behavior

it should not give this error 
From my little research I found out this error comes when an x86 executable is tested on arm

### Steps To Reproduce

Git clone repo on arm vps (oracle) / pi4 
make start in the repo directory

### Environment

```markdown
- OS: Ubuntu
- Version: Ubuntu 20.04.6 LTS

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

### Anything else?
Make it compatible with arm as many selfhosted entusiasts run pi or low power arm sbc
I just deployed this repo on a fresh vps and it gave me this error 

And a wiki on how to use it would be helpful like the ip:port we need to put in app to connect the backup node like that ?

**Comment by fb929** [comment]
hi !
@bolavefasfas what exactly arch You have?
I use macos arm M1 and don't have this problem.
Show me please output command "uname -a" from any docker container.

**Comment by bolavefasfas** [comment]
> hi ! @bolavefasfas what exactly arch You have? I use macos arm M1 and don't have this problem. Show me please output command "uname -a" from any docker container.

Oracle arm vps
