### ISSUE TITLE
Self Host Error

### ISSUE THREAD

**Issue by Kerblif** [anyproto/any-sync-dockercompose#92]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

After installing the config and creating a new account, I get a Self Host Error

### Expected Behavior

I will get an OK message and working sync

### Steps To Reproduce

1) make start
2) install EXTERNAL_LISTEN_HOST
3) make restart

### Environment

```markdown
- OS: Ubuntu 22
- Version: latest
```

**Comment by Kerblif** [comment]
The error is that forced generation of .env is being started, overwriting the changes.
When I deleted the item with env generation, everything worked for me

**Comment by fb929** [comment]
This is not an error; we're using auto-generation for the `.env` file.
The necessary changes you need to make should be applied to the `.env.override` file.
You can find more information about this here https://github.com/anyproto/any-sync-dockercompose/wiki/Configuration

**Comment by Kerblif** [comment]
Okay. Maybe it's worth adding information about this to the main ReadMe?
