### ISSUE TITLE
Image synchronization issues

### ISSUE THREAD

**Issue by anschein** [anyproto/any-sync-dockercompose#97]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Sorry using self-hosting is a bit out of my league, I tried self-hosting on top of the homeserver and it worked, but when I connect the client to the node, any additional multimedia content such as documents, images, etc. are not synchronized except for text type content, I tried to check the docker container's logs, and I see the error entries, however I can't troubleshoot due to limited capabilities

### Expected Behavior

Correctly synchronize all types of files

### Steps To Reproduce

![image](https://github.com/user-attachments/assets/3e45d87d-4f52-403e-b06b-d6b94d7c46af)

### Environment

```markdown
- OS:Ubuntu 22.04
ANY_SYNC_NODE_VERSION=v0.3.34
ANY_SYNC_FILENODE_VERSION=v0.6.7
ANY_SYNC_COORDINATOR_VERSION=v0.3.28
ANY_SYNC_CONSENSUSNODE_VERSION=v0.1.7
```

**Comment by fb929** [comment]
It seems that your bucket wasn't created in Minio.
Please show the output of the command:
```docker-compose logs create-bucket```

Also, the version of any-sync-dockercompose is needed: ```git rev-parse HEAD```

**Comment by anschein** [comment]
> It seems that your bucket wasn't created in Minio. Please show the output of the command: `docker-compose logs create-bucket`
> 
> Also, the version of any-sync-dockercompose is needed: `git rev-parse HEAD`

Thanks for help
The `git rev-parse HEAD` output is 82b9ec1ce96f5bb2ae56ff036f31a8aa0ccf72e7
And `docker-compose logs create-bucket` shows nothing,I'm checking in Portainer,the 
any-sync-dockercompose-create-bucket-1 container stopped with exit code 0

<img width="760" alt="截屏2024-10-02 22 08 25" src="https://github.com/user-attachments/assets/242c3758-292b-4377-bb44-f52517e9d754">

**Comment by fb929** [comment]
> The `git rev-parse HEAD` output is [82b9ec1](https://github.com/anyproto/any-sync-dockercompose/commit/82b9ec1ce96f5bb2ae56ff036f31a8aa0ccf72e7)

You have a version with broken logic in `create-bucket`. 
I recommend updating to the latest release:
```
git checkout v5.0.4
```

Don't forget to review the [update instructions](https://github.com/anyproto/any-sync-dockercompose/wiki/Upgrade-Guide#upgrading-from-v4xx-to-v5xx)

**Comment by anschein** [comment]
When I deleted the data directory and repulled the docker installation everything was fine, but not long after that the problem of not being able to synchronize the images arose again, this time with the following error report, this is the error log I found in filenode, I don't know if it has anything to do with the issue of synchronizing the images
![image](https://github.com/user-attachments/assets/f81f505f-a9ee-40eb-90ec-cdcb29bf40da)
![image](https://github.com/user-attachments/assets/f6acf9c4-ce9e-4f61-b8ae-1e1c95de4a4f)

**Comment by fb929** [comment]
You most likely ran out of memory on Redis, but it's also possible that you hit the memory limit in your Docker Compose configuration. In any case, you should check the container limits and the daemon logs to confirm this.

I have noted that you added the variable `ANY_SYNC_DAEMONS_MEMORY_LIMIT` for regulating the memory limit of any-sync-* daemons.
You can try it in [this](https://github.com/anyproto/any-sync-dockercompose/tree/97-image-synchronization-issues) branch

**Comment by anschein** [comment]
> You most likely ran out of memory on Redis, but it's also possible that you hit the memory limit in your Docker Compose configuration. In any case, you should check the container limits and the daemon logs to confirm this.
> 
> I have noted that you added the variable `ANY_SYNC_DAEMONS_MEMORY_LIMIT` for regulating the memory limit of any-sync-* daemons. You can try it in [this](https://github.com/anyproto/any-sync-dockercompose/tree/97-image-synchronization-issues) branch

I didn't add any other variables except the external IP, when this problem occurred I noticed it was a memory problem, I tried to increase the memory limit for the filenode in the portainer but it didn't solve the problem

**Comment by fb929** [comment]
> Could there be problems with synchronization due to redis' memory release policy?

yes, that's possible. It seems like you might have a large number of files?

**Comment by fb929** [comment]
You’ve added the REDIS_MAXMEMORY variable

**Comment by anschein** [comment]
After updating the configuration of the main branch and setting REDIS_MAXMEMORY, when the synchronized node is turned on for an extended period of time there is still an “error”: “1 error occurred:\n\t* node #0: OOM command not allowed when used memory > ' maxmemory'. \n\n”, ‘app’: ‘v0.6.7’, Regardless of what I set the max memory of redis to, I wonder if ‘--maxmemory-policy’: ‘noeviction’ is causing the problem?

**Comment by anschein** [comment]
> After updating the configuration of the main branch and setting REDIS_MAXMEMORY, when the synchronized node is turned on for an extended period of time there is still an “error”: “1 error occurred:\n\t* node #0: OOM command not allowed when used memory > ' maxmemory'. \n\n”, ‘app’: ‘v0.6.7’, Regardless of what I set the max memory of redis to, I wonder if ‘--maxmemory-policy’: ‘noeviction’ is causing the problem?

I'll try to test by removing the entry in docker-compose

**Comment by fb929** [comment]
The "noeviction" policy is set intentionally and cannot be changed. It seems you have a large number of files, so you need to increase your limits.
