### ISSUE TITLE
can't generate an invite link & sync images

### ISSUE THREAD

**Issue by tubleronchik** [anyproto/any-sync-dockercompose#98]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Hi there. I try to run a self hosted Anytype and while it works fine for with type content (it synchronizes properly). But I'm encountering an issue when trying to create a shared space and generate an invitation link. The following error appears (I removed ids):
```
store invite in ipfs: add file to sync queue: walk file blocks: process batch: select blocks to upload: add to file: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method. status code: 403, request id: <>, host id: <>,
generate invite
```
I checked logs from the container and can see the same error there:
```
docker logs any-sync-dockercompose-any-sync-filenode-1
{"totalDur": 0.010399035, "spaceId": "", "size": 319, "cid": "", "fileId": "", "error": "SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: , host id: ", "app": "v0.6.7", "peerId": "", "identity": "", "rpc": "file.blockPush", "peerVersion": "Linux:0.42.8/middle:v0.35.7/any-sync:"}
```
I'm seeing this issue across multiple clients: Ubuntu (v0.42.8), macOS (v0.42.8), and iOS (iPhone, v0.32.3). Additionally, it seems that any content type other than text cannot be synchronized — I receive the same error when attempting to add an image.

Please let me know if you need any additional logs or information.

### Expected Behavior

Generate invite link. Correctly synchronize all types of files. 

### Steps To Reproduce

I followed the procedure as mentioned in the wiki, then created a new space, made it shared and tried to  generate an invitation link. 

### Environment

```markdown
- OS:Ubuntu
- Version: 24.04 LTS 

grep 'ANY_SYNC_.*_VERSION=' .env.default
ANY_SYNC_NODE_VERSION=prod
ANY_SYNC_FILENODE_VERSION=prod
ANY_SYNC_COORDINATOR_VERSION=v0.3.26
ANY_SYNC_CONSENSUSNODE_VERSION=prod
ANY_SYNC_TOOLS_VERSION=latest
```

**Comment by fb929** [comment]
Please show your version of the self-hosted repository: `git rev-parse HEAD`

**Comment by fb929** [comment]
and can you show me the synchronization status on the client, please?
It should look something like this: 
<img width="1436" alt="Screenshot 2024-10-09 at 14 23 08" src="https://github.com/user-attachments/assets/e4eb7114-82a7-4694-bea3-f65f38002817">

**Comment by tubleronchik** [comment]
Sure. This is an empty space containing only text objects, as far as I understand, and these are being synchronized.
![image](https://github.com/user-attachments/assets/363aa9d5-de28-46e3-b44f-b200e77dcf0f)
This is the default space. However, every time another type of content is created here (I’m not sure why since I don't create it), that content is not being synchronized.
![image](https://github.com/user-attachments/assets/76527469-8c63-4c1d-90e6-16727314b5c0)

**Comment by fb929** [comment]
can you show me the client, filenode, and coordinator logs, please?
client logs: you need to run client from console, logs will be on stdout
```
ANYTYPE_LOG_LEVEL="*=DEBUG" ANYPROF=:6060 ANY_SYNC_NETWORK=<path/to/client.yml> /Applications/Anytype.app/Contents/MacOS/Anytype
```

filenode and coordinator:
```
docker-compose logs any-sync-filenode
docker-compose logs any-sync-coordinator
```

**Comment by tubleronchik** [comment]
client logs (Ubuntu client v.0.42.8) (I removed part of ids)::
```
{"level":"ERROR","ts":"2024-10-10T21:17:52.571+0200","logger":"filesync","msg":"retry uploading file error","fileId":"bafybeidqjngtnh22b43hkud7be2gt74dp7sq5nwx2av7h5tunq5uybugaa","error":"walk file blocks: walk DAG: process batch: select blocks to upload: add to file: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: 17FD2D82DB340645, host id: dd9025<>; SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: 17FD2D82DDCBA3B4, host id: dd9025<>; SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: 17FD2D82E0608890, host id: dd9025b<>; SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: 17FD2D82E2ABD3BA, host id: dd9025<>; SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: 17FD2D82E4D6B8EE, host id: dd9025<>; SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: 17FD2D82E6FB0175, host id: dd9025<>; SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: 17FD2D82EFE73DBF, host id: dd9025<>; SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: 17FD2D82F27D4315, host id: dd9025<>; SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: 17FD2D82F4C4C7A4, host id: dd9025<>; SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: 17FD2D82F714EDD2, host id: dd9025<>","objectId":"bafyreig54hu7kenm6z7ltaluvuoc3qnfn2xlrlcdr33s2dkchj552kovdu"}
```
Additionally, I've the following error:
``` {"level":"ERROR","ts":"2024-10-10T21:13:43.165+0200","logger":"any-pp.drpcclient","msg":"no payment processing peers configured"} ```

----
filenode logs (I removed part of ids):
```
INFO    rpcLog          {"totalDur": 0.007423745, "spaceId": "bafyrei<>", "size": 106, "cid": "bafybeibrkttiv<>", "fileId": "bafybeidqjngtnh<>", "error": "SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: 17FD2D82F4C4C7A4, host id: dd9025<>", "app": "v0.6.7", "peerId": "12D3KooWSBaNU<>", "identity": "A7rJAgW8dc9<>", "rpc": "file.blockPush", "peerVersion": "Linux:0.42.8/middle:v0.35.7/any-sync:v0.4.30"}
```
----
coordinator logs: I'm not sure which logs from the coordinator I should provide so here is some errors or warnings which I can see
```
WARN    common.net.connutil     can't set write deadline        {"remoteAddr": "172.18.0.11:54364"}
any-sync-coordinator-1  | 2024-10-10T19:24:46.151Z      INFO    common.net.peer serve connection error  {"error": "manager closed: EOF", "errorVerbose": "manager closed: EOF\n\tstorj.io/drpc/drpcmanager.(*Manager).manageReader:234"}
```

**Comment by taoyuan** [comment]
I have the same issue

**Comment by TaoRone** [comment]
I had a similar problem after I redeployed today
Through my testing, I found that if I upload an image through the PC side (windows11), for example an 800kb photo, it can be uploaded successfully over the network, and then through a non-LAN Android device (latest version client side: 0.32.41) can successfully sync the photo and display it (occasionally need to exit the app and re-enter to display it)
But on the other hand, if I upload a photo on my Android phone, the green dot in the upper left corner of the Android phone prompts that it has been synced, but the synchronization on the PC side is always in progress (near photos, text is not affected)
Tomorrow, I will try to sync with another win PC and an IOS device. If there are any new findings, I will continue to post them.
Hope to provide you with a reference.

**Comment by fb929** [comment]
@tubleronchik 
These lines are not enough, I need the full log.  
The log is safe to share, as it doesn't contain keys, only IDs.
However, if you'd like, you can obfuscate the IDs by replacing them with any "stream editor", like `sed`.

Alternatively, you can send the logs to me on Telegram, nickname `@fb_929`

**Comment by tubleronchik** [comment]
> These lines are not enough, I need the full log.

hi again, sorry for misunderstanding. Here is my logs, but they are brief because I only ran Anytype for a short time. Let me know if you need additional logs

[coordinator.log](https://github.com/user-attachments/files/17369534/coordinator.log)
[filenode.log](https://github.com/user-attachments/files/17369535/filenode.log)
[ubuntu_client.log](https://github.com/user-attachments/files/17369536/ubuntu_client.log)

**Comment by fb929** [comment]
It looks like the bucket wasn't created in MinIO; we had an issue with this in one of the recent versions.
Check the service logs:
```
docker-compose logs create-bucket
```

To fix this, perform the update:
```
git checkout v5.0.4 && make restart
```

**Comment by tubleronchik** [comment]
here is my bucket logs before update:

[bucket.log](https://github.com/user-attachments/files/17393039/bucket.log)

After update the logs remained the same and the images still couldn't be synchronize. I also tried to clean everything (using `make cleanEtcStorage`) and then run again `make start`. Here is the bucket after it:
 
[bucket_new.log](https://github.com/user-attachments/files/17393141/bucket_new.log)

**Comment by tubleronchik** [comment]
I found the problem. I changed `AWS_SECRET_ACCESS_KEY` (adding a new one to `.env.override`). After I've changed it to default value all works fine

**Comment by console4711** [comment]
First of all, super awesome work!! 🙏 

I'm still running into the exact same problem, i.e. images not synching and I cannot create invite links, i.e.
```
store invite in ipfs: add file to sync queue: walk file blocks: process batch: select blocks to upload: add to file: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method. status code: 403, request id: <>, host id: <>
```

I'm running Ubuntu server 24.04 and access it via local network. My overrides look like this

```
AWS_ACCESS_KEY_ID=changed_this
AWS_SECRET_ACCESS_KEY=secret

MONGO_VERSION=4.4.29
EXTERNAL_LISTEN_HOST="192.168.100.XX"

# had to change this since 8081 is used
ANY_SYNC_NODE_1_API_SERVER_ADDR=127.0.0.1:8087
ANY_SYNC_NODE_1_METRIC_ADDR=127.0.0.1:8007

STORAGE_DIR="/new/path"
```

```
services:
  mongo-1:
    healthcheck:
      test: echo "rs.initiate({_id:'${MONGO_REPLICA_SET}',members:[{_id:0,host:\"mongo-1:${MONGO_1_PORT}\"}]}).ok || rs.status().ok" | mongo --port ${MONGO_1_PORT} --quiet
```

@fb929 any idea what I'm doing wrong?
We can change the `AWS_SECRET_ACCESS_KEY` as long as it is consistent from startup I imagine @tubleronchik?

**Comment by fb929** [comment]
@console4711 You need to determine which user/password actually exists in MinIO, and which user owns the bucket.  
Then compare that with what have saved in `./etc/.aws/credentials`.

**Comment by console4711** [comment]
Thanks for the pointer @fb929! I did

- compare `./etc/.aws/credentials` with `.env`: they match
- attach to `minio` container
  - verify that `MINIO-BUCKET` has been created (and it has)
    - `mc alias set minio http://127.0.0.1:9000 "${MINIO_ROOT_USER}" "${MINIO_ROOT_PASSWORD}"`
    - check that bucket exists
      ```
      # mc ls minio             
      [2025-04-18 22:04:49 UTC]     0B minio-bucket/
      ```
  - double check that `env` inside container match credentials of `./etc/.aws/credentials`
- `minio.mc` logs
    ```
    mc: <ERROR> Unable to make bucket `minio/minio-bucket`. Your previous request to create the named bucket succeeded and you already own it.
    ```

Any idea what I'm missing?

**Comment by fb929** [comment]
I can’t reproduce your issue.  
I’m changing `AWS_SECRET_ACCESS_KEY` on an existing self-hosted setup and not encountering any problems.

You're adding the new `AWS_SECRET_ACCESS_KEY` to `.env.override`, right?  
And you’re performing a full restart of the setup with:

```bash
make stop
make start
```  

correct?

**Comment by console4711** [comment]
Thanks for your help looking into this @fb929!

Yes, I redid it again and removed Server setup + Windows App + iOS installation. My steps
- `make stop`
- `make clean`
- `make cleanEtcStorage` (make sure it's actually deleted due to access right issues)
- Uninstall Windows app + delete `AppData` folder
- Uninstall from phone
- Double check overrides, same as in https://github.com/anyproto/any-sync-dockercompose/issues/98#issuecomment-2816600604 but added `MINIO_BUCKET=anytype-bucket`
- `make start`
- I just made a screenshot and added it to newly created profile -> still not synchronizing images
  - ![Image](https://github.com/user-attachments/assets/dd10eba7-bd96-4c7d-8975-ac230a719354)
- Generating link doesn't work
  ```bash
  store invite in ipfs: add file to sync queue: walk file blocks: process batch: select blocks to upload: add to file: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method. status code: 403, request id: 1<id>, host id: <id>, generate invite
  ``` 
- Inside `minio` container
  ```bash
  sh-5.1# mc alias set minio http://127.0.0.1:9000 "${MINIO_ROOT_USER}" "${MINIO_ROOT_PASSWORD}"
  Added `minio` successfully.
  sh-5.1# mc ls minio
  [2025-04-26 08:12:14 UTC]     0B anytype-bucket/
  sh-5.1# mc ls minio/anytype-bucket
  ```
- Logs of `minio/mc` container
  ```bash
  docker logs --tail 1000 -f 9160d2cde25e48[...]54617 

  mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "http://minio:9000/probe-bsign-[..]xht/?location=": dial tcp 172.19.0.3:9000: connect: connection refused.
  ...waiting...
  Added `minio` successfully.
  Bucket created successfully `minio/anytype-bucket`.
  ```

Other notes
- Firewall shouldn't be the issue: `sudo ufw status; Status: inactive`
- I also tried adding `network` to the main `docker-compose.yml`, but didn't work
- After another fresh setup: `docker-compose logs | grep -i error > error_logs.txt` and `docker-compose logs > logs.txt`
  - [error_logs.txt](https://github.com/user-attachments/files/19921590/error_logs.txt)
  - [logs.txt](https://github.com/user-attachments/files/19921671/logs.txt)

**Comment by fb929** [comment]
> AWS_SECRET_ACCESS_KEY=secret  

I assume you're actually using a different secret?

I’ve fully replicated your settings, but I still can’t reproduce the problem :\  
from the logs, it looks like the S3 ACL settings for MinIO and Filenode don’t match.  
try checking it this way:

1. Check the settings for Filenode 
    ```
    $ docker compose exec any-sync-filenode cat /root/.aws/credentials
    [default]
    aws_access_key_id=changed_this
    aws_secret_access_key=secret11E
    ```
    ```
    $ docker compose exec any-sync-filenode grep -A 8 '^s3Store' /etc/any-sync-filenode/config.yml
    s3Store:
      bucket: anytype-bucket
      indexBucket: anytype-bucket
      maxThreads: 16
      profile: default
      region: us-east-1
      endpoint: http://minio:9000
      forcePathStyle: true # 'true' for self-hosted S3 Object Storage
    redis:
    ```
2. Check the settings for MinIO
    ```
    $ docker compose exec minio cat /proc/1/environ ;echo
    MINIO_UPDATE_MINISIGN_PUBKEY=RWTx5Zr1tiHQLwG9keckT0c45M3AGeHD6IvimQHpyRywVWGbP1aVSGavMINIO_ROOT_PASSWORD=secret11EMINIO_SECRET_KEY_FILE=secret_keyHOSTNAME=6cc5d2199766MINIO_CONFIG_ENV_FILE=config.envPWD=/MINIO_ROOT_USER_FILE=access_keyHOME=/rootMINIO_ACCESS_KEY_FILE=access_keyMINIO_ROOT_USER=changed_thisSHLVL=0MINIO_KMS_SECRET_KEY_FILE=kms_master_keyMC_CONFIG_DIR=/tmp/.mcPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/binMINIO_ROOT_PASSWORD_FILE=secret_key
    ```
    here you need to find `MINIO_ROOT_PASSWORD` and `MINIO_ROOT_USER`.
3. Compare them to ensure they match


### **also !**
1. I need the version of the `any-sync-dockercompose` repository: `git rev-parse HEAD`
2. the versions of the clients
3. the versions of the server components:
    ```
    for I in any-sync-node-{1..3}; do docker compose exec $I any-sync-node -v; done

    for I in any-sync-node-{1..3}; do docker compose exec $I any-sync-node -v; done
    ```

**Comment by mecp** [comment]
facing the same issue 

```sh
$ any-sync-dockercompose git:(main) ✗ git rev-parse HEAD
b3ec97cc8c14ed1701d4daa54f48690e96210c3a
```

image tags are set to `latest`

**Comment by mecp** [comment]
now fixed, secret key had `!` character in it, which caused history expansion issue in `processing.sh`
