### ISSUE TITLE
File syncing issues

### ISSUE THREAD

**Issue by XurxoMF** [anyproto/any-sync-dockercompose#99]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Pages, Sets and all content in general it's getting synced with the self-hosted server but images are not.
Images keep loading forever, on P2P too.

### Expected Behavior

IMages getting synced as any other file.

### Steps To Reproduce

Idk, it was working fine since I started using the self-host option(2 months +-) and now it's not.

### Environment

```markdown
- OS: Windows 11, Android 14 and Linux as server
- Version: Latest versions on everything, I've updated all 3 apps and server like 2 days ago.
```

### Anything else?

![imagen](https://github.com/user-attachments/assets/94748611-0740-4002-b5f6-632d186fb5ec)
![imagen](https://github.com/user-attachments/assets/02806be2-ea13-40b7-b6cc-f619ce140d71)

**Comment by fb929** [comment]
can you show logs from filenode and coordinator, please
```
docker-compose logs any-sync-filenode
docker-compose logs any-sync-coordinator
```

**Comment by CharellKing** [comment]
![image](https://github.com/user-attachments/assets/b9ba94ff-effd-4419-a9fe-e98ef8d160a3)

**Comment by CharellKing** [comment]
this is filenode log
![image](https://github.com/user-attachments/assets/92074897-16a9-4814-9131-2fa8f94092e6)

**Comment by CharellKing** [comment]
now i use the lastest image, this is .env.override
![image](https://github.com/user-attachments/assets/169fdb5f-6939-4624-9d68-586dd629eeb5)

**Comment by XurxoMF** [comment]
Coordinator:
https://drive.google.com/file/d/1w2C1uImazKO8O_wSQ0RplA15LsbyyCHc/view?usp=sharing
Filenode:
https://drive.google.com/file/d/1gXS5gIxwDYNq3bsRRC4GZOWllP0Xnuoy/view?usp=sharing

150MB + each lol. I uploaded them to drive bc I was nto able to share them here directly ^^

**Comment by XurxoMF** [comment]
I've updated again and now it's working.

It was already on 5.0.4 but maybe something went wrong while updating last time or idk....

For now on it's working, let's see what happens on the next few days.

**Comment by fb929** [comment]
> Coordinator: https://drive.google.com/file/d/1w2C1uImazKO8O_wSQ0RplA15LsbyyCHc/view?usp=sharing Filenode: https://drive.google.com/file/d/1gXS5gIxwDYNq3bsRRC4GZOWllP0Xnuoy/view?usp=sharing
> 
> 150MB + each lol. I uploaded them to drive bc I was not able to share them here directly ^^
> 
> Comment: Firewalls and router forwards are open and working fine, just in case.


It looks more like your any-sync-coordinator has crashed based on the log:
```
any-sync-dockercompose-any-sync-filenode-1  | 2024-10-11T12:45:40.276Z  INFO    net.peerservice can't connect to host   {"rootOp": "periodicCall", "addr": "any-sync-coordinator:1004", "error": "dial tcp:
lookup any-sync-coordinator on 127.0.0.11:53: server misbehaving"}
any-sync-dockercompose-any-sync-filenode-1  | 2024-10-11T12:45:40.276Z  INFO    net.peerservice can't connect to host   {"rootOp": "periodicCall", "addr": "192.168.18.3:1004", "error": "dial tcp 192.168.1
8.3:1004: connect: connection refused"}
any-sync-dockercompose-any-sync-filenode-1  | 2024-10-11T12:45:40.278Z  INFO    net.peerservice can't connect to host   {"rootOp": "periodicCall", "addr": "185.229.156.90:1004", "error": "dial tcp 185.229
.156.90:1004: connect: connection refused"}
any-sync-dockercompose-any-sync-filenode-1  | 2024-10-11T12:45:40.278Z  INFO    net.peerservice can't connect to host   {"rootOp": "periodicCall", "addr": "127.0.0.1:1004", "error": "dial tcp 127.0.0.1:10
04: connect: connection refused"}
any-sync-dockercompose-any-sync-filenode-1  | 2024-10-11T12:45:40.278Z  INFO    net.peerservice can't connect to host   {"rootOp": "periodicCall", "addr": "quic://any-sync-coordinator:1014", "error": "loo
kup any-sync-coordinator on 127.0.0.11:53: server misbehaving"}
any-sync-dockercompose-any-sync-filenode-1  | 2024-10-11T12:45:50.279Z  INFO    net.peerservice can't connect to host   {"rootOp": "periodicCall", "addr": "quic://192.168.18.3:1014", "error": "timeout: no
 recent network activity"}
```

According to the log, the coordinator daemon was stopped gracefully:
```
any-sync-dockercompose-any-sync-coordinator-1  | 2024-09-23T03:53:43.494Z   INFO    main    received exit signal, stop app...   {"signal": "terminated"}
```

The update only helped you because it triggered a restart of all daemons.
And I do not recommend using the latest versions, as they may include incompatible test versions.

**Comment by CharellKing** [comment]
Thank you.
